#!/bin/bash
#
# Lint your latest commit!
#

if [ ! -d ".git" ]; then
  echo ""
  echo "This script must be run from the repo's top-level directory."
  echo "Go back and try again."
  echo ""
  exit 1
fi

function find_exclude() {
 find . -name "$1" -not \( -path "./node_modules/*" -prune \)
 }

echo ""
find_exclude '*.js' | xargs ./node_modules/jshint/bin/jshint --config .jshint.json
