#!/bin/bash
#
# Lint your latest commit!
#

if [ ! -d ".git" ]; then
  echo ""
  echo "This script must be run from the repo's top-level directory."
  echo "Go back and try again."
  echo ""
  exit 1
fi

function find_exclude() {
 find . -name "$1" -not \( -path "./node_modules/*" -prune \)
}

echo ""
find_exclude '*.js' | xargs \
  node node_modules/js-beautify/js/bin/js-beautify --config .js-beautify.json -r

find_exclude '*.html' | xargs \
  node node_modules/js-beautify/js/bin/html-beautify -r

find_exclude '*.css' | xargs \
  node node_modules/js-beautify/js/bin/css-beautify -r
